agents:
  queue: linux-medium

env:
  CI: "true"
  CARGO_TERM_COLOR: always
  INSTA_UPDATE: "no"

steps:
  - label: ":rust: Linux build and unit tests"
    key: build
    commands:
      - source .buildkite/setup.sh
      - cargo build --workspace --locked
      - cargo nextest run --locked --no-fail-fast
      - cargo nextest run -p tests-support --locked --no-fail-fast
    timeout_in_minutes: 30

  - label: ":test_tube: Integration %N/%t"
    key: integration
    commands:
      - source .buildkite/setup.sh
      - bash .buildkite/test.sh integration
    parallelism: 8
    timeout_in_minutes: 30

  - label: ":terminal: End-to-end %N/%t"
    key: e2e
    commands:
      - source .buildkite/setup.sh
      - bash .buildkite/test.sh e2e
    parallelism: 4
    timeout_in_minutes: 30
