[package]
name = "building"
version = "0.1.0"
edition = "2024"

[dependencies]
building-types = { version = "0.1.0", path = "../building-types" }
checking = { version = "0.1.0", path = "../checking" }
documenting = { version = "0.1.0", path = "../documenting" }
files = { version = "0.1.0", path = "../files" }
foreign-javascript = { version = "0.1.0", path = "../../compiler-backend/foreign-javascript" }
indexing = { version = "0.1.0", path = "../indexing" }
interner = { version = "0.1.0", path = "../interner" }
javascript = { version = "0.1.0", path = "../../compiler-backend/javascript" }
lexing = { version = "0.1.0", path = "../../compiler-frontend/lexing" }
lock_api = "0.4.14"
lowering = { version = "0.1.0", path = "../lowering" }
nbe = { version = "0.1.0", path = "../../compiler-backend/nbe" }
parking_lot = "0.12.5"
parsing = { version = "0.1.0", path = "../parsing" }
prim-constants = { version = "0.1.0", path = "../prim-constants" }
resolving = { version = "0.1.0", path = "../resolving" }
rustc-hash = "2.1.3"
stabilizing = { version = "0.1.0", path = "../stabilizing" }
sugar = { version = "0.1.0", path = "../sugar" }
smol_str = "0.3.2"
ssa = { version = "0.1.0", path = "../../compiler-backend/ssa" }
thread_local = "1.1.10"

[dev-dependencies]
la-arena = "0.3.1"
