[package]
name = "diagnostics"
version = "0.1.0"
edition = "2024"

[dependencies]
files = { version = "0.1.0", path = "../files" }
foreign-javascript = { version = "0.1.0", path = "../../compiler-backend/foreign-javascript" }
indexing = { version = "0.1.0", path = "../../compiler-frontend/indexing" }
lowering = { version = "0.1.0", path = "../lowering" }
resolving = { version = "0.1.0", path = "../resolving" }
checking = { version = "0.1.0", path = "../checking" }
stabilizing = { version = "0.1.0", path = "../../compiler-frontend/stabilizing" }
syntax = { version = "0.1.0", path = "../../compiler-frontend/syntax" }

lsp-types.workspace = true
line-index = "0.1.2"
itertools = "0.15.0"
smol_str = "0.3.2"
