[package]
name = "tests-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
analyzer = { version = "0.1.0", path = "../compiler-lsp/analyzer" }
async-lsp = "0.2.4"
building = { version = "0.1.0", path = "../compiler-core/building" }
checking = { version = "0.1.0", path = "../compiler-core/checking" }
diagnostics = { version = "0.1.0", path = "../compiler-core/diagnostics" }
documentation = { version = "0.1.0", path = "../compiler-lsp/documentation" }
files = { version = "0.1.0", path = "../compiler-core/files" }
glob = "0.3.4"
indexing = { version = "0.1.0", path = "../compiler-core/indexing" }
interner = { version = "0.1.0", path = "../compiler-core/interner" }
itertools = "0.15.0"
insta = "1.48.0"
line-index = "0.1.2"
lowering = { version = "0.1.0", path = "../compiler-core/lowering" }
lsp-types.workspace = true
nbe = { version = "0.1.0", path = "../compiler-backend/nbe" }
prim-constants = { version = "0.1.0", path = "../compiler-core/prim-constants" }
serde_json = "1.0"
similar = "3"
ssa = { version = "0.1.0", path = "../compiler-backend/ssa" }
stabilizing = { version = "0.1.0", path = "../compiler-core/stabilizing" }
sugar = { version = "0.1.0", path = "../compiler-core/sugar" }
syntax = { version = "0.1.0", path = "../compiler-core/syntax" }
tabled = "0.21.0"
tempfile = "3.27.0"
url = "2.5.8"

[dev-dependencies]
datatest-stable = "0.3"

[[test]]
name = "backend"
harness = false

[[test]]
name = "checking"
harness = false

[[test]]
name = "semantic"
harness = false

[[test]]
name = "lowering"
harness = false

[[test]]
name = "resolving"
harness = false

[[test]]
name = "lsp"
harness = false

[[test]]
name = "nbe"
harness = false

[[test]]
name = "docs"
harness = false
