name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Install Rust toolchain
        run: rustup update stable && rustup default stable

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.9.1
        with:
          cache-bin: "false"
          prefix-key: "v1-codspeed"

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target(s)
        run: >
          cargo codspeed build -m simulation
          -p documenting
          -p tests-compatibility --bench parsing --bench stabilizing

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
